In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
arr = np.zeros((9,9))
arr[:,0] = 1
arr[:,1] = 1
arr[:,2] = 1
arr[8,:] = 1
arr[4,5], arr[7,7], arr[1,8] = 1,1,1
print(arr)

[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [ ]:
plt.show()

In [25]:
plt.spy(arr)

In [26]:
plt.savefig('lab6Image')